# Site Settings
title: My Resume
url: 'http://agiletech.vn'
baseurl: 'https://agiletechvn.github.io' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Pham Tran Tuan
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I`am Tuan, 24 years old full-stack developer, working as a Software Engineering in Agile Tech Viet Nam in Ha Noi, Viet Nam. I have 3 years of research experience in some subject of computer science, 1 year of research experience in theory of modern cryptography while i studied Computer Science at HUST ( Ha Noi university of science & technology ), 1 years of experience in react, node, express, graphql, web design, mongodb, etc. 

 My ultimate goal is to obtain a career that will allow myself to take full advantage of my passion and experience in software engineering, computer science and development operations.
'

#sidebar links
email: tuan.pham@agiletech.vn 
phone: 012 345 6789
website: cloudatlas93.wordpress.com #do not add http://
github: p77u4n
twitter: '@tuanpt93'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-119187154-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
